-   id: commitlint
    name: commitlint
    description: ''
    entry: commitlint --edit
    language: node
    'types': [text]
    args: []
    require_serial: false
    additional_dependencies: ["commitlint@17.6.5"]
    minimum_pre_commit_version: '0'
