name: main
on:
  push:
    branches: [main]
  schedule:
  - cron: '15 8 * * *'

jobs:
  build:
    name: main
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
    - run: pip install pre-commit-mirror-maker
    - run: git config --global user.name 'Github Actions'
    - run: git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
    - run: pre-commit-mirror . --language=node --package-name=commitlint --types=text --entry='commitlint --edit' --id=commitlint
    - run: |
        cat <<END >> .pre-commit-hooks.yaml
        -   id: commitlint-all
            name: commitlint-all
            description: ''
            entry: commitlint --from --
            language: node
            'types': [text]
            args: []
            require_serial: false
            additional_dependencies: ["commitlint@$(git describe --tags --abbrev=0 | cut -c2-)"]
            minimum_pre_commit_version: '0'
        END
    - run: |
        git remote set-url origin https://x-access-token:$GH_TOKEN@github.com/$GITHUB_REPOSITORY
        git push origin HEAD:refs/heads/main --tags
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
